---
- name: Delete key files
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/tmp/id_ssh_rsa.pub"
    - "/tmp/id_ssh_rsa"

- name: "Delete SSH Key Private"
  uri:
    url: "https://{{ whmhostname }}:2087/json-api/cpanel"
    method: "POST"
    headers:
      Authorization: "whm {{ whmusername }}:{{ whmtoken }}"
    body:
      cpanel_jsonapi_user: "{{ item.user }}"
      cpanel_jsonapi_apiversion: "2"
      cpanel_jsonapi_module: "SSH"
      cpanel_jsonapi_func: "delkey"
      name: "{{ keyname }}"
    body_format: form-urlencoded
  register: sshkeydel
  with_items: "{{ cpanelaccounts.json.acct }}"

- name: "Delete SSH Key Public"
  uri:
    url: "https://{{ whmhostname }}:2087/json-api/cpanel"
    method: "POST"
    headers:
      Authorization: "whm {{ whmusername }}:{{ whmtoken }}"
    body:
      cpanel_jsonapi_user: "{{ item.user }}"
      cpanel_jsonapi_apiversion: "2"
      cpanel_jsonapi_module: "SSH"
      cpanel_jsonapi_func: "delkey"
      name: "{{ keyname }}.pub"
    body_format: form-urlencoded
  register: sshkeydelpublic
  with_items: "{{ cpanelaccounts.json.acct }}"

- name: "Debug"
  debug:
    var: sshkeydel
    verbosity: 1

- name: "Debug"
  debug:
    var: sshkeydelpublic
    verbosity: 1